services:
  - type: web
    name: qr-attendance
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: default
